mydata = {
    "lip gloss" : "I sell a lip gloss",
    "cup" : "I sell a cup",
    "computer" : "I sell a computer",
    "grid paper" : "I sell a grid paper",
    "plate": "I sell a plate",
    "box": "I sell a box",
    "thermostat": "I sell a thermostat",
    "lace": "I sell a lace",
    "knife": "I sell a knife",
    "rug": "I sell a rug",
    "car": "I sell a car",
    "soda can": "I sell a soda can",
    "hanger": "I sell a hanger",
    "street lights": "I sell street lights",
    "cell phone": "I sell a cell phone",
    "tissue box": "I sell a tissue box",
    "bowl": "I sell a bowl",
    "floor": "I sell a floor",
    "rubber duck": "I sell a rubber duck",
    "sticky note": "I sell a sticky note",
    "balloon": "I sell a balloon",
    "chapter book": "I sell a chapter book",
    "food": "I sell food",
    "TV": "I sell a TV",
    "socks": "I sell socks",
    "glass": "I sell a glass",
    "sketch pad": "I sell a sketch pad",
    "milk": "I sell a milk",
    "blouse": "I sell a blouse",
    "tree": "I sell a tree",
    "bottle": "I sell a bottle",
    "eraser": "I sell a eraser",
    "magnet": "I sell a magnet",
    "wallet": "I sell a wallet",
    "mouse pad": "I sell a mouse pad",
    "pants": "I sell a pants",
    "doll": "I sell a doll",
    "glow stick" : "I sell a glow stick",
    "newspaper" : "I sell a newspaper",
    "piano": "I sell a piano",
    "bread" : "I sell bread",
    "plastic fork" : "I sell a plastic fork",
    "glasses": "I sell a glasses",
    "playing card": "I sell playing card",
    "cork": "I sell a cork",
    "water bottle": "I sell a water bottle",
    "charger": "I sell a charger",
    "keyboard": "I sell a keyboard",
    "bow": "I sell a bow",
    "house": "I sell a house",
}